EMBEDDING_DEPLOYMENT_ID = "d7b8e46fc3d5c25f"
LLM_DEPLOYMENT_ID = "d01dff41125cfa27"
EMBEDDING_TABLE = "EMBEDDINGS_CODEJAM_NORA"
SEMANTIC_EMBEDDING_TABLE = "EMBEDDINGS_CODEJAM_+<YOUR_NAME>"+"_SEMANTIC"

# You could for example try chunk size 100
# EMBEDDING_TABLE_CHUNK_SIZE_100 = "EMBEDDINGS_CODEJAM_+<YOUR_NAME>"+"CHUNK_SIZE_100"

DEPLOYMENT_ID_MULTIMODAL = ""